[package]
name = "rusty-chip8"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bracket-terminal = "0.8"
log = "0.4"
env_logger = "0.9"
anyhow = "1.0"
structopt = "0.3"
